# Generated by Django 3.2.5 on 2021-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('distance', models.FloatField(default=0, help_text='Distance covered in jog in meters')),
                ('time', models.FloatField(default=0, help_text='Total jog time in seconds')),
                ('location', models.CharField(max_length=255)),
                ('weather', models.JSONField(max_length=255)),
            ],
        ),
    ]
