# Generated by Django 3.2.5 on 2021-08-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joggingapi', '0003_alter_jogrecord_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogrecord',
            old_name='jogger_id',
            new_name='jogger',
        ),
    ]
